import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ position: "relative" }}>
        {children}
        <a
          style={{
            position: "absolute",
            top: "100px",
            left: "30px",
            backgroundColor: "aliceblue",
            padding: "8px 24px",
            fontColor: "white",
            borderRadius: "100px",
            zIndex: 100,
          }}
          href="/"
        >
          home
        </a>
        <a
          style={{
            position: "absolute",
            top: "150px",
            left: "30px",
            backgroundColor: "aliceblue",
            padding: "8px 24px",
            fontColor: "white",
            borderRadius: "100px",
            zIndex: 100,
          }}
          href="/cylinder"
        >
          cylinder
        </a>
        <a
          style={{
            position: "absolute",
            top: "200px",
            left: "30px",
            backgroundColor: "aliceblue",
            padding: "8px 24px",
            fontColor: "white",
            borderRadius: "100px",
            zIndex: 100,
          }}
          href="/pointcloud"
        >
          pointcloud
        </a>
        <a
          style={{
            position: "absolute",
            top: "250px",
            left: "30px",
            backgroundColor: "aliceblue",
            padding: "8px 24px",
            fontColor: "white",
            borderRadius: "100px",
            zIndex: 100,
          }}
          href="/json_pointcloud"
        >
          json_pointcloud
        </a>
      </body>
    </html>
  );
}
