import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Pretendard, nexon, NotoSansKR, spoqa, waterfall } from "./libs/fonts";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${Pretendard.className} ${nexon.variable} ${NotoSansKR.variable} ${spoqa.variable} ${waterfall.variable}`}
    >
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
